# Generated by Django 3.2.12 on 2023-08-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_serviceprovider_supportstaff_task_taskattachment_taskcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment_information',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferences',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('cash', 'Cash'), ('offline_payment', 'Offline Payment'), ('partial_payment', 'Partial Payments')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='availability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='skills',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
