# Generated by Django 3.2.12 on 2023-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customer_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
