# Generated by Django 3.2.12 on 2023-09-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230814_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_location', models.CharField(max_length=100)),
                ('delivery_datetime', models.DateTimeField()),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('electronics', 'Electronics'), ('jewelry', 'Jewelry')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=100)),
                ('pickup_datetime', models.DateTimeField()),
                ('additional_notes', models.TextField(blank=True)),
            ],
        ),
    ]
