# Generated by Django 3.2.12 on 2023-09-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delivery_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_delivery', to='users.delivery'),
        ),
        migrations.AddField(
            model_name='task',
            name='pickup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_pickup', to='users.pickup'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('pickup_delivery', 'Pickup and Delivery'), ('cleaning', 'Cleaning Service (Coming Soon)'), ('task_delegation', 'Task Delegation (Coming Soon)')], max_length=20),
        ),
    ]
