# Generated by Django 3.2.12 on 2023-09-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.DeleteModel(
            name='DishCategory',
        ),
    ]
